#!/bin/sh
# build-installer.sh — generate a self-contained, self-extracting installer for this skill.
#
# Bundles SKILL.md + scripts/ into a tar.gz, base64-encodes it, and appends it as a blob to the
# end of a POSIX shell template. The resulting dist/install.sh extracts the bundle and runs
# `remote.mjs register`. It supports both `sh install.sh` (reads the blob from $0) and
# `curl -fsSL <url>/install.sh | sh` (reads the blob from the same stdin the shell consumes).
#
# Usage: ./build-installer.sh [output-path]   (default: dist/install.sh)
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd)
OUT="${1:-$ROOT/dist/install.sh}"
MARKER='__ARCHIVE_BELOW__'

command -v tar >/dev/null 2>&1 || { echo "build: tar is required" >&2; exit 1; }
command -v base64 >/dev/null 2>&1 || { echo "build: base64 is required" >&2; exit 1; }

# Sanity: the things we ship must exist.
[ -f "$ROOT/SKILL.md" ] || { echo "build: SKILL.md not found" >&2; exit 1; }
[ -d "$ROOT/scripts" ] || { echo "build: scripts/ not found" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"

TARBALL=$(mktemp "${TMPDIR:-/tmp}/ai1-bundle.XXXXXX.tgz")
trap 'rm -f "$TARBALL"' EXIT INT TERM

# Build the bundle.
#   COPYFILE_DISABLE  stops bsdtar (macOS) from emitting ._ AppleDouble entries.
#   --no-xattrs / --no-mac-metadata  stop macOS xattrs (e.g. com.apple.provenance) from being
#   stored as LIBARCHIVE extended headers, which trigger "Ignoring unknown extended header
#   keyword" warnings when extracted with a non-Apple tar. Both flags are best-effort: any the
#   local tar doesn't understand are dropped.
echo "build: bundling SKILL.md + scripts/ ..." >&2
TAR_OPTS="--exclude=.DS_Store"
for opt in --no-xattrs --no-mac-metadata; do
  if tar "$opt" -cf /dev/null -C "$ROOT" SKILL.md >/dev/null 2>&1; then
    TAR_OPTS="$TAR_OPTS $opt"
  fi
done
# shellcheck disable=SC2086
COPYFILE_DISABLE=1 tar -C "$ROOT" $TAR_OPTS -czf "$TARBALL" SKILL.md scripts

BYTES=$(wc -c < "$TARBALL" | tr -d ' ')
echo "build: bundle is ${BYTES} bytes (compressed)" >&2

# Emit the runtime template. Quoted heredoc => no expansion here; $0/$@/etc. stay literal.
# The LAST line is the marker; the base64 blob is appended immediately after it.
cat > "$OUT" <<TEMPLATE_EOF
#!/bin/sh
# ai1-crhq-installer — self-extracting installer (GENERATED by build-installer.sh; do not edit).
#
# Layout: shell logic, then \`exit 0\`, then the line \`${MARKER}\`, then a base64 tar.gz blob.
#
# Usage:
#   curl -fsSL <url>/install.sh | sh
#   curl -fsSL <url>/install.sh | sh -s -- --hub=https://hub.example --token=SECRET
#   sh install.sh [extra register args...]
#
# Configuration (environment):
#   AI1_INSTALL_DIR    where to extract the bundle (default: a fresh temp dir)
#   AI1_RUN_REGISTER   set to 0 to extract only and skip \`remote.mjs register\`
#   AI1_HUB_URL / AI1_BOOTSTRAP_TOKEN  (plus any CLI args) are passed straight to register.
set -eu

MARKER='${MARKER}'

die() { echo "ai1-installer: \$*" >&2; exit 1; }

usage() {
  cat <<'USAGE_EOF'
ai1-crhq-installer — self-extracting installer

Extracts the bundled skill (SKILL.md + scripts/) and registers this satellite
with the Ai1 Platform Hub via \`remote.mjs register\`.

Usage:
  curl -fsSL <url>/install.sh | sh
  curl -fsSL <url>/install.sh | sh -s -- [register args...]
  sh install.sh [register args...]

Options:
  -h, --help   show this help and exit (does not extract or register)

All other arguments are forwarded to \`remote.mjs register\` (e.g. --hub=, --token=,
--remote-id=, --force). To see register's own options, extract first then run it:
  AI1_RUN_REGISTER=0 sh install.sh && node \$AI1_INSTALL_DIR/scripts/remote.mjs register --help

Environment:
  AI1_INSTALL_DIR    where to extract the bundle (default: a fresh temp dir)
  AI1_RUN_REGISTER   set to 0 to extract only and skip register
  AI1_HUB_URL        hub base URL, passed to register
  AI1_BOOTSTRAP_TOKEN  enrollment secret, passed to register
USAGE_EOF
}

# Pick a base64 decoder that exists (GNU --decode / -d, BSD -D, or openssl).
b64decode() {
  if base64 --decode </dev/null >/dev/null 2>&1; then base64 --decode
  elif base64 -d </dev/null >/dev/null 2>&1; then base64 -d
  elif base64 -D </dev/null >/dev/null 2>&1; then base64 -D
  elif command -v openssl >/dev/null 2>&1; then openssl base64 -d
  else die "no base64 decoder found (need base64 or openssl)"
  fi
}

# Stream just the base64 blob to stdout. File mode reads \$0; piped mode reads stdin — in both
# cases "delete everything up to and including the marker line" leaves exactly the blob, so any
# preceding shell lines (e.g. the trailing \`exit 0\`) consumed in piped mode are stripped too.
payload() {
  if [ -f "\$0" ] && grep -q "^\${MARKER}\$" "\$0" 2>/dev/null; then
    sed -e "1,/^\${MARKER}\$/d" "\$0"
  else
    sed -e "1,/^\${MARKER}\$/d"
  fi
}

run_register() {
  echo "ai1-installer: extracted bundle to \$INSTALL_DIR" >&2
  if [ "\${AI1_RUN_REGISTER:-1}" = "0" ]; then
    echo "ai1-installer: AI1_RUN_REGISTER=0 — skipping register" >&2
    return 0
  fi
  command -v node >/dev/null 2>&1 || die "node (>=18) is required to run register"
  echo "ai1-installer: running remote.mjs register ..." >&2
  node "\$INSTALL_DIR/scripts/remote.mjs" register "\$@"
}

main() {
  for arg in "\$@"; do
    case "\$arg" in
      -h|--help) usage; exit 0 ;;
    esac
  done

  command -v tar >/dev/null 2>&1 || die "tar is required"

  INSTALL_DIR="\${AI1_INSTALL_DIR:-\$(mktemp -d "\${TMPDIR:-/tmp}/ai1-crhq-installer.XXXXXX")}" \\
    || die "could not create install dir"
  mkdir -p "\$INSTALL_DIR" || die "could not create \$INSTALL_DIR"

  payload | b64decode | tar xzf - -C "\$INSTALL_DIR" || die "failed to extract bundle"
  [ -f "\$INSTALL_DIR/scripts/remote.mjs" ] || die "bundle missing scripts/remote.mjs"

  run_register "\$@"
}

main "\$@"
exit 0
${MARKER}
TEMPLATE_EOF

# Append the blob. base64 default line-wrapping differs across platforms but the decoder
# tolerates either wrapped or single-line input.
base64 < "$TARBALL" >> "$OUT"

chmod +x "$OUT"
echo "build: wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)" >&2
