#!/bin/sh
# build-installer.sh — generate a self-contained, self-extracting installer for this skill.
#
# Bundles SKILL.md + scripts/ into a tar.gz, base64-encodes it, and appends it as a blob to the
# end of a POSIX shell template. The resulting dist/install.sh extracts the bundle, installs the
# package, and registers the satellite with the Ai1 Platform Hub. It supports both
# `sh install.sh` (reads the blob from $0) and `curl -fsSL <url>/install.sh | sh` (reads the
# blob from the same stdin the shell consumes).
#
# Usage: ./build-installer.sh [output-path]   (default: dist/install.sh)
set -eu

ROOT=$(cd "$(dirname "$0")" && pwd)
OUT="${1:-$ROOT/dist/install.sh}"
MARKER='__ARCHIVE_BELOW__'

command -v tar >/dev/null 2>&1 || { echo "build: tar is required" >&2; exit 1; }
command -v base64 >/dev/null 2>&1 || { echo "build: base64 is required" >&2; exit 1; }

# Sanity: the things we ship must exist.
[ -f "$ROOT/ai1-package.yaml" ] || { echo "build: ai1-package.yaml not found" >&2; exit 1; }
[ -f "$ROOT/SKILL.md" ] || { echo "build: SKILL.md not found" >&2; exit 1; }
[ -f "$ROOT/README.md" ] || { echo "build: README.md not found" >&2; exit 1; }
[ -d "$ROOT/docs" ] || { echo "build: docs/ not found" >&2; exit 1; }
[ -d "$ROOT/scripts" ] || { echo "build: scripts/ not found" >&2; exit 1; }
[ -f "$ROOT/install-satellite-tools.sh" ] || { echo "build: install-satellite-tools.sh not found" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"

PKG_VERSION=$(grep '^version:' "$ROOT/ai1-package.yaml" | head -1 | sed 's/^version:[[:space:]]*//')
[ -n "$PKG_VERSION" ] || { echo "build: could not read version from ai1-package.yaml" >&2; exit 1; }
TARBALL="$ROOT/dist/ai1-satellite@${PKG_VERSION}.tgz"

# Stage the package layout into a local directory we keep around for inspection.
# The skill directory is assembled here from root sources; scripts/, docs/, README.md
# and SKILL.md all land under skills/ai1-satellite-tools/ so the installer copies them
# to SKILLS_BASE_DIR/ai1-satellite-tools/ as skill assets. We stage into a real dir
# (rather than tar --transform/-s) because GNU and BSD tar spell those differently.
STAGEDIR="$ROOT/dist/package"
echo "build: staging package layout in $STAGEDIR ..." >&2
rm -rf "$STAGEDIR"
mkdir -p "$STAGEDIR"
BUILD_DATE=$(date '+%Y%m%d')
awk -v build="build: ${BUILD_DATE}.0" '/^version:/{print; print build; next}1' \
  "$ROOT/ai1-package.yaml" > "$STAGEDIR/ai1-package.yaml"
mkdir -p "$STAGEDIR/scripts"
cp "$ROOT/install-satellite-tools.sh" "$STAGEDIR/scripts/"
mkdir -p "$STAGEDIR/skills/ai1-satellite-tools"
cp "$ROOT/SKILL.md"   "$STAGEDIR/skills/ai1-satellite-tools/SKILL.md"
cp "$ROOT/README.md"  "$STAGEDIR/skills/ai1-satellite-tools/README.md"
cp -rp "$ROOT/docs"    "$STAGEDIR/skills/ai1-satellite-tools/docs"
cp -rp "$ROOT/scripts" "$STAGEDIR/skills/ai1-satellite-tools/scripts"

# Build the tarball from the staged layout.
#   COPYFILE_DISABLE  stops bsdtar (macOS) from emitting ._ AppleDouble entries.
#   --no-xattrs / --no-mac-metadata  stop macOS xattrs (e.g. com.apple.provenance) from being
#   stored as LIBARCHIVE extended headers, which trigger "Ignoring unknown extended header
#   keyword" warnings when extracted with a non-Apple tar. Both flags are best-effort: any the
#   local tar doesn't understand are dropped.
echo "build: bundling staged package ..." >&2
TAR_OPTS="--exclude=.DS_Store"
for opt in --no-xattrs --no-mac-metadata; do
  if tar "$opt" -cf /dev/null -C "$STAGEDIR" ai1-package.yaml >/dev/null 2>&1; then
    TAR_OPTS="$TAR_OPTS $opt"
  fi
done
# shellcheck disable=SC2086
COPYFILE_DISABLE=1 tar -C "$STAGEDIR" $TAR_OPTS -czf "$TARBALL" ai1-package.yaml scripts skills

BYTES=$(wc -c < "$TARBALL" | tr -d ' ')
echo "build: bundle is ${BYTES} bytes (compressed)" >&2

# Emit the runtime template. Unquoted heredoc — ${}/${} in the template must be \$-escaped to
# survive as literals in the generated script. ${MARKER} is intentionally unescaped so its
# build-time value is embedded. The LAST non-blob line is the marker; the base64 blob follows.
cat > "$OUT" <<TEMPLATE_EOF
#!/bin/sh
# AGENT INSTRUCTIONS — ai1-satellite-tools self-extracting installer
# Generated by build-installer.sh; do not edit this file directly.
#
# PURPOSE
#   Extract the embedded ai1-satellite-tools bundle, install it as an Ai1
#   Package, then register this satellite with the Ai1 Platform Hub.
#
# PRECONDITIONS
#   - node >= 18 on PATH (required for install and register steps)
#   - tar and a base64 decoder (base64 or openssl) on PATH
#   - Hub URL and bootstrap token required for registration.
#     AGENT: if AI1_BOOTSTRAP_TOKEN is not already set, ask the operator for
#     the token using a secure/hidden input method, then export it into the
#     environment before running this script. Do NOT pass it as --token= (it
#     would be visible in process listings).
#
# STEPS (executed in order)
#   1. Decode + extract embedded tar.gz to INSTALL_DIR
#   2. node INSTALL_DIR/skills/ai1-satellite-tools/scripts/install.mjs INSTALL_DIR
#   3. node INSTALL_DIR/skills/ai1-satellite-tools/scripts/remote.mjs register ...
#
# INVOCATION
#   sh install.sh [register-args...]
#   curl -fsSL <url>/install.sh | sh -s -- [register-args...]
#
# ENVIRONMENT
#   AI1_INSTALL_DIR       extraction root (default: ~/packages/ai1-satellite-tools)
#   AI1_RUN_INSTALL       set to 0 to skip step 2
#   AI1_RUN_REGISTER      set to 0 to skip step 3
#   AI1_HUB_URL           hub base URL forwarded to register
#   AI1_BOOTSTRAP_TOKEN   enrollment secret (AGENT: set in env before running;
#                          do not pass as --token= — visible in process listings)
#
# CLI ARGS
#   -h | --help   print this block and exit
#   All other args are forwarded to remote.mjs register
#   (e.g. --hub=<url>, --remote-id=<id>, --force)
#   To inspect register options without running:
#     AI1_RUN_INSTALL=0 AI1_RUN_REGISTER=0 sh install.sh
#     node \${AI1_INSTALL_DIR:-\${HOME}/packages/ai1-satellite-tools}/skills/ai1-satellite-tools/scripts/remote.mjs register --help
set -eu

MARKER='${MARKER}'

die() { echo "ai1-installer: \$*" >&2; exit 1; }

usage() {
  cat <<'USAGE_EOF'
ai1-satellite-tools — self-extracting installer

Extracts the bundled ai1-satellite-tools package, installs it, and registers
this satellite with the Ai1 Platform Hub.

Steps:
  1. Extract embedded bundle to INSTALL_DIR
  2. node INSTALL_DIR/skills/ai1-satellite-tools/scripts/install.mjs INSTALL_DIR
  3. node INSTALL_DIR/skills/ai1-satellite-tools/scripts/remote.mjs register [args]

Usage:
  sh install.sh [register-args...]
  curl -fsSL <url>/install.sh | sh -s -- [register-args...]

Options:
  -h, --help   show this help and exit

Environment:
  AI1_INSTALL_DIR       extraction root (default: ~/packages/ai1-satellite-tools)
  AI1_RUN_INSTALL       set to 0 to skip package install step
  AI1_RUN_REGISTER      set to 0 to skip register step
  AI1_HUB_URL           hub base URL forwarded to register
  AI1_BOOTSTRAP_TOKEN   enrollment secret (prompted securely if absent)

All non-option args are forwarded to remote.mjs register.
USAGE_EOF
}

# Pick a base64 decoder that exists (GNU --decode / -d, BSD -D, or openssl).
b64decode() {
  if base64 --decode </dev/null >/dev/null 2>&1; then base64 --decode
  elif base64 -d </dev/null >/dev/null 2>&1; then base64 -d
  elif base64 -D </dev/null >/dev/null 2>&1; then base64 -D
  elif command -v openssl >/dev/null 2>&1; then openssl base64 -d
  else die "no base64 decoder found (need base64 or openssl)"
  fi
}

# Stream just the base64 blob to stdout. File mode reads \$0; piped mode reads stdin — in both
# cases "delete everything up to and including the marker line" leaves exactly the blob.
payload() {
  if [ -f "\$0" ] && grep -q "^\${MARKER}\$" "\$0" 2>/dev/null; then
    sed -e "1,/^\${MARKER}\$/d" "\$0"
  else
    sed -e "1,/^\${MARKER}\$/d"
  fi
}

run_install_pkg() {
  if [ "\${AI1_RUN_INSTALL:-1}" = "0" ]; then
    echo "ai1-installer: AI1_RUN_INSTALL=0 — skipping package install" >&2
    return 0
  fi
  command -v node >/dev/null 2>&1 || die "node (>=18) is required"
  echo "ai1-installer: running install.mjs ..." >&2
  node "\$INSTALL_DIR/skills/ai1-satellite-tools/scripts/install.mjs" "\$INSTALL_DIR"
}

run_register() {
  if [ "\${AI1_RUN_REGISTER:-1}" = "0" ]; then
    echo "ai1-installer: AI1_RUN_REGISTER=0 — skipping register" >&2
    return 0
  fi
  command -v node >/dev/null 2>&1 || die "node (>=18) is required to run register"
  echo "ai1-installer: running remote.mjs register ..." >&2
  node "\$INSTALL_DIR/skills/ai1-satellite-tools/scripts/remote.mjs" register "\$@"
}

main() {
  for arg in "\$@"; do
    case "\$arg" in
      -h|--help) usage; exit 0 ;;
    esac
  done

  command -v tar >/dev/null 2>&1 || die "tar is required"

  INSTALL_DIR="\${AI1_INSTALL_DIR:-\${HOME}/packages/ai1-satellite-tools}"
  mkdir -p "\$INSTALL_DIR" || die "could not create \$INSTALL_DIR"

  payload | b64decode | tar xzf - -C "\$INSTALL_DIR" || die "failed to extract bundle"
  [ -f "\$INSTALL_DIR/skills/ai1-satellite-tools/scripts/remote.mjs" ] || die "bundle missing skills/ai1-satellite-tools/scripts/remote.mjs"
  echo "ai1-installer: extracted bundle to \$INSTALL_DIR" >&2

  run_install_pkg
  run_register "\$@"
}

main "\$@"
exit 0
${MARKER}
TEMPLATE_EOF

# Append the blob. base64 default line-wrapping differs across platforms but the decoder
# tolerates either wrapped or single-line input.
base64 < "$TARBALL" >> "$OUT"

chmod +x "$OUT"
echo "build: wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)" >&2
echo "build: tarball kept at $TARBALL ($(wc -c < "$TARBALL" | tr -d ' ') bytes)" >&2
